{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FFT Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(mgr_fft_duration_seconds_count{}[$__interval])"
    }
   ]
  },
  {
   "title": "Files Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(mgr_file_processing_duration_seconds_count{}[$__interval])"
    }
   ]
  },
  {
   "title": "Aggregate FFT Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(mgr_fft_duration_seconds_count{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Aggregate Files Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(mgr_fft_duration_seconds_count{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Mean FFT Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(mgr_fft_duration_seconds_sum{}[$__interval]))/sum(rate(mgr_fft_duration_seconds_count[$__interval])) "
    }
   ]
  },
  {
   "title": "Mean File Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(mgr_file_processing_duration_seconds_sum{}[$__interval]))/sum(rate(mgr_file_processing_duration_seconds_count{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(mgr_request_processing_duration_seconds_count{}[$__interval])"
    }
   ]
  },
  {
   "title": "Aggregate Requests Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(mgr_request_processing_duration_seconds_count{}[$__interval]))"
    }
   ]
  },
  {
   "title": "Mean Request Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(mgr_request_processing_duration_seconds_sum{}[$__interval]))/sum(rate(mgr_request_processing_duration_seconds_count{}[$__interval]))"
    }
   ]
  },
  {
   "title": "FFT Duration Buckets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 33 },
   "targets": [
    {
     "expr": "mgr_fft_duration_seconds_bucket"
    }
   ]
  }
 ]
}